# Generated by Django 3.0.6 on 2021-09-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Location',
            new_name='location',
        ),
    ]
