# Generated by Django 3.0.6 on 2021-09-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remarkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkmodel',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.TaskModel'),
            preserve_default=False,
        ),
    ]
