# Generated by Django 3.0.6 on 2021-09-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remarkmodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarkmodel',
            name='task',
        ),
    ]
