# Generated by Django 3.0.6 on 2021-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210921_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('0', 'new'), ('1', 'in_progress'), ('2', 'hold'), ('3', 'complete'), ('4', 'reject')], default='new', max_length=20),
        ),
    ]
