# Generated by Django 3.0.6 on 2021-09-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_taskmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='status',
            new_name='task_status',
        ),
    ]
