# Generated by Django 3.0.6 on 2021-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_userstatusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(choices=[('0', 'employee'), ('1', 'manager')], default='employee', max_length=20),
        ),
    ]
