# Generated by Django 3.0.6 on 2021-09-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210927_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
