# Generated by Django 3.0.6 on 2021-09-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20210927_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
