# Generated by Django 3.0.6 on 2021-09-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20210927_1653'),
        ('login', '0016_auto_20210927_1653'),
    ]

    operations = [
    ]
