# Generated by Django 3.0.6 on 2021-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_merge_20210927_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='UserStatusModel',
        ),
    ]
