# Generated by Django 3.0.6 on 2021-10-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20210928_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasonmodel',
            name='reason',
        ),
        migrations.AddField(
            model_name='reasonmodel',
            name='reason_hold',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reasonmodel',
            name='reason_reject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
